version: "3"
services:
  db:
    container_name: rails_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Tokyo
  nginx:
    container_name: rails_nginx
    build: ./docker/nginx
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - ./public:/app/public
      - ./tmp:/app/tmp
  app:
    container_name: rails_app
    build: .
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Asia/Tokyo
      - RAILS_ENV=production
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  redis:
    container_name: rails_redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Tokyo